# This workflow updates all open PRs if their base branch is pushed to
# https://github.com/chinthakagodawita/autoupdate
name: Auto-update open PRs
on:
  # This will trigger on all pushes to all branches
  push: {}
  # Alternatively, you can only trigger if commits are pushed to certain branches, e.g.:
  # push:
  #   branches:
  #     - master
jobs:
  autoupdate:
    name: Auto-update open PRs
    runs-on: ubuntu-latest
    steps:
      - uses: chinthakagodawita/autoupdate-action@699da47083dddb66e5f5d2d48825b2e375a1d6c3 #v0.1.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_MSG: "Branch was auto-updated with the latest."
          MERGE_CONFLICT_ACTION: ignore
