# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To view the configuration, go to: .github/labeler.yml
name: Auto-label PRs

on:
  pull_request:
    types: [opened, convert_to_draft, ready_for_review]
  pull_request_review:
    types: [submitted]

env:
  TOKEN: "${{ secrets.GITHUB_TOKEN }}"

# Separate jobs can run concurrently
jobs:
  triage:
    name: Apply triage labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ env.TOKEN }}"

  mergeable:
    name: Flag a PR ready to merge
    runs-on: ubuntu-latest

    steps:
      - name: Flag ready to merge
        # Add a ready to merge label if the PR is approved and the test suite has passed
        if: |
          !contains(github.event.pull_request.labels.*.name, 'on hold') &&
          !contains(github.event.pull_request.labels.*.name, 'work in progress') &&
          github.event.review.state == 'approved' &&          
          github.event.check_suite.status == 'completed' &&
          github.event.check_suite.conclusion == 'success'
        uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf #v1
        with:
          github_token: ${{ env.TOKEN }}
          labels: ready to merge

  in-progress:
    name: Flag a PR as work-in-progress if in draft
    runs-on: ubuntu-latest

    steps:
      - name: Flag work in progress
        if: github.event.pull_request.draft == true
        uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf #v1
        with:
          github_token: ${{ env.TOKEN }}
          labels: work in progress
